apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: ${region}
  version: "1.22"

managedNodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 3
    spot: true